### ISSUE TITLE
Add default mxout to lagoon-remote chart

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-charts#178]
Something like:
```
kind: Service
apiVersion: v1
metadata:
  name: mxout
  namespace: lagoon
spec:
  type: ExternalName
  externalName: mxout1.example.com
```
