### ISSUE TITLE
k8up.schedule and k8up.secret in lagoon-core don't preserve existing values

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon-charts#344]
The fixes introduced in #327 to bring k8up to lagoon-core don't seem to be able to handle pre-existing bucket names and schedules.

Running a helmfile diff generates a new bucket and secret every time:
```
lagoon-core, lagoon-core, Schedule (backup.appuio.ch) has changed:
  # Source: lagoon-core/templates/k8up.schedule.yaml
  apiVersion: backup.appuio.ch/v1alpha1
  kind: Schedule
  metadata:
    name: lagoon-core
  spec:
    backend:
      repoPasswordSecretRef:
        key: repo-pw
        name: "lagoon-core-baas-repo-pw"
      s3:
        
-       bucket: baas-lagoon-core-iymbqkas
+       bucket: baas-lagoon-core-2jog9pxp

lagoon-core, lagoon-core-baas-repo-pw, Secret (v1) has changed:
  # Source: lagoon-core/templates/k8up.secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: lagoon-core-baas-repo-pw
  data:
-   repo-pw: '-------- # (28 bytes)'
+   repo-pw: '++++++++ # (28 bytes)'
```
