### ISSUE TITLE
Support TCP application logs in lagoon-logging

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon-charts#661]
lagoon-logging currently supports UDP for application logs.

In order to support more logging transports more easily (such as Winston, Pino etc), we should also accept TCP logs on a separate port

**Comment by smlx** [comment]
I took a look at [the docs](https://docs.fluentd.org/parser/json). fluentd JSON parser expects one object per line (newline delimited). This is configurable but the default is simplest.

So adding a port on the [statefulset](https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml#L64C1-L66C28):

```yaml
        - containerPort: 5140
          protocol: TCP
          name: application_tcp
```

The [service](https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-logging/templates/logs-dispatcher.service.yaml#L28):

```yaml
  - name: application_tcp
    port: 5140
    protocol: TCP
    targetPort: application_tcp
```

And a snippet like this to the [fluent config](https://github.com/uselagoon/lagoon-charts/blob/main/charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml#L35) should do the trick (totally untested):

```
    <source>
      @type  tcp
      @id    in_application_tcp
      tag    "lagoon.#{ENV['CLUSTER_NAME']}.application"
      port   5140
      <parse>
        @type json
      </parse>
    </source>
```

And then we need to document how to get logs there in the right format. And note that if you don't escape newlines (so a line has half a JSON object), the log message will be dropped.
